### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [tojorodialson/hc-laravel#4]
Hi,

Your package can't be installed by using Composer if we have PHP8.
Do you have planned to make support?

Thank you.
Best regards,

**Comment by tojorodialson** [comment]
@Jars-of-jam-Scheduler Hello!
Sorry for late, I'm busy and I haven't lot time now
Thank you for your feedback. But If you can contribute with package, I can give you an access
Regards,

**Comment by tojorodialson** [comment]
> Hi,
> 
> Your package can't be installed by using Composer if we have PHP8.
> Do you have planned to make support?
> 
> Thank you.
> Best regards,

Support php 8, done!
